# Generated by Django 4.0.5 on 2022-08-04 16:48

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Recipes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='static/posts')),
                ('title', models.CharField(blank=True, max_length=50, null=True)),
                ('ingredients', models.TextField(max_length=500)),
                ('description', models.TextField(max_length=1500)),
            ],
        ),
    ]
