# Generated by Django 4.0.5 on 2022-08-22 16:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipe', '0003_alter_recipe_description'),
    ]

    operations = [
        migrations.CreateModel(
            name='Food',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='static/posts')),
                ('title', models.CharField(blank=True, max_length=50, null=True)),
            ],
        ),
    ]
